const firebaseErrors = {
  // Auth
  "auth/email-already-in-use": "Este e-mail já está em uso.",
  "auth/invalid-email": "O e-mail informado é inválido.",
  "auth/weak-password": "A senha é muito fraca. Use pelo menos 6 caracteres.",
  "auth/operation-not-allowed": "Tipo de autenticação desativado. Contate o suporte.",
  "auth/internal-error": "Erro interno no servidor. Tente novamente mais tarde.",
  "auth/network-request-failed": "Erro de conexão. Verifique sua internet.",
  "auth/user-not-found": "Usuário não encontrado. Verifique o e-mail informado.",
  "auth/wrong-password": "Senha incorreta. Tente novamente.",
  "auth/too-many-requests": "Muitas tentativas falhas. Tente novamente mais tarde.",
  "auth/user-disabled": "Esta conta foi desativada. Contate o suporte.",
  "auth/missing-email": "O e-mail é obrigatório.",
  "auth/missing-password": "A senha é obrigatória.",
  "auth/popup-closed-by-user": "O pop-up foi fechado antes da conclusão do login.",
  "auth/cancelled-popup-request": "A solicitação de pop-up foi cancelada.",
  "auth/popup-blocked": "O navegador bloqueou o pop-up. Libere para continuar.",
  "auth/credential-already-in-use": "Essa credencial já está associada a outra conta.",
  "auth/account-exists-with-different-credential": "Já existe uma conta com esse e-mail. Use o provedor correto.",
  "auth/invalid-credential": "Credencial inválida. Tente novamente.",
  "auth/missing-verification-code": "Código de verificação ausente.",
  "auth/invalid-verification-code": "Código de verificação inválido ou expirado.",
  "auth/missing-verification-id": "ID de verificação ausente.",
  "auth/requires-recent-login": "Faça login novamente para realizar essa operação.",
  "auth/invalid-login-credentials": "Credenciais inválidas.",
  "auth/email-already-exists": "Este e-mail já está vinculado a uma conta.",
  "auth/invalid-user-token": "Sessão expirada. Faça login novamente.",
  // Firestore
  "permission-denied": "Você não tem permissão para acessar esses dados.",
  "not-found": "Documento ou coleção não encontrado.",
  "unavailable": "Serviço temporariamente indisponível. Tente novamente mais tarde.",
  "deadline-exceeded": "Tempo de resposta excedido. Verifique sua conexão.",
  "resource-exhausted": "Limite de leitura ou escrita excedido. Aguarde um momento.",
  "aborted": "Operação cancelada. Tente novamente.",
  "already-exists": "Este recurso já existe.",
  "cancelled": "A operação foi cancelada.",
  "data-loss": "Falha irreversível. Dados podem ter sido corrompidos.",
  "failed-precondition": "Precondições não atendidas para realizar a operação.",
  "internal": "Erro interno. Tente novamente mais tarde.",
  "invalid-argument": "Argumento inválido fornecido.",
  "out-of-range": "Valor fora do intervalo permitido.",
  "unauthenticated": "Você precisa estar autenticado para realizar esta operação.",
  "unimplemented": "Esta funcionalidade ainda não está implementada.",
  "unknown": "Erro desconhecido.",
  // Storage
  "storage/unknown": "Erro desconhecido de armazenamento.",
  "storage/object-not-found": "Arquivo não encontrado.",
  "storage/bucket-not-found": "Bucket não encontrado.",
  "storage/project-not-found": "Projeto do Firebase não encontrado.",
  "storage/quota-exceeded": "Limite de armazenamento excedido.",
  "storage/unauthenticated": "Você precisa estar autenticado para fazer isso.",
  "storage/unauthorized": "Você não tem permissão para acessar este arquivo.",
  "storage/retry-limit-exceeded": "Limite de tentativas excedido. Tente novamente mais tarde.",
  "storage/invalid-checksum": "O arquivo foi corrompido durante o envio.",
  "storage/canceled": "Envio ou download cancelado.",
  "storage/invalid-event-name": "Nome de evento inválido.",
  "storage/invalid-url": "URL inválida.",
  "storage/invalid-argument": "Argumento inválido fornecido.",
  "storage/no-default-bucket": "Nenhum bucket padrão foi configurado.",
  "storage/cannot-slice-blob": "Erro ao processar o arquivo para upload.",
  "storage/server-file-wrong-size": "O tamanho do arquivo no servidor está incorreto.",
};

export function getErrorMessage(code) {
  return firebaseErrors[code] || "Erro desconhecido. Tente novamente.";
}